In [2]:
from pyforest import *

In [5]:
lst = []
r = int(input('Enter the number of rows:'))
c = int(input('Enter the number of columns:'))
for i in range(r*c):
    lst.append(int(input('Enter the elements:')))
platform = np.array(lst).reshape(r,c)

Enter the number of rows:4
Enter the number of columns:6
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:1
Enter the elements:2
Enter the elements:3
Enter the elements:1
Enter the elements:3
Enter the elements:3
Enter the elements:1
Enter the elements:2
Enter the elements:3
Enter the elements:1
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:3
Enter the elements:1
Enter the elements:3
Enter the elements:3


In [9]:

def WaterStoredInPlatform(platform):

    z = np.max(platform)

    water = np.ones((z+1,r,c))

    for level in range(0,z):
        water[level] = np.where(platform-level <= 0, 1, 0)

    water[0] *= 2  


    for level in range(0,z+1):


        zero = np.argwhere(water[level] == 1)

        for i,j in zero:
            if j == 0 or i == 0 or i == r-1 or j == c-1:
                water[level,i,j] = 2

        count = np.count_nonzero(water[level] == 2)
        oldcount = 0

        spill = np.argwhere(water[level] == 2)

        while oldcount != count:

            oldcount = count

            for i,j in spill:
                if j-1 >= 0:
                    if water[level,i,j-1] == 1:
                        water[level,i,j-1] = 2
                if j+1 < c:
                    if water[level,i,j+1] == 1:
                        water[level,i,j+1] = 2
                if i+1 < r:
                    if water[level,i+1,j] == 1:
                        water[level,i+1,j] = 2
                if i-1 >= 0:
                    if water[level,i-1,j] == 1:
                        water[level,i-1,j] = 2
                if level+1 <= z:
                    if water[level+1,i,j] == 1:
                        water[level+1,i,j] = 2

            spill = np.argwhere(water[level] == 2)
            count = np.count_nonzero(water[level] == 2)

        water[level] = np.where(water[level] == 1, 1, 0)
        print(f"level {level}\n{water[level]}")


    totalcubes = np.sum(water)
    print('\nTotal water blocks = ',totalcubes)

WaterStoredInPlatform(platform)


level 0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
level 1
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
level 2
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
level 3
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Total water blocks =  10.0


In [19]:
z = np.max(platform)
water = np.ones((z+1,r,c))
for level in range(0,z):
        water[level] = np.where(platform-level <= 0, 1, 0)
water

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [21]:
platform

array([[3, 3, 3, 3, 3, 3],
       [3, 1, 2, 3, 1, 3],
       [3, 1, 2, 3, 1, 3],
       [3, 3, 3, 1, 3, 3]])

In [22]:
water[0] *= 2

In [23]:
water

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [24]:
for level in range(0,z+1):
    zero = np.argwhere(water[level] == 1)

In [25]:
zero

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5]])